openapi: 3.0.2
info:
  title: API Clube do Vinho
  description: |-
    API responsável por gerenciar o ClubeDoVinho:
    - Categorias (Category)
    - Clientes (Customer)
    - Compras (Purchase)
    - Países (Country)
    - Products (Product)

    Links Importantes:
    - [Github](https://github.com/alessandrofeitoza/clubedovinho)

  license:
    name: GPLv3
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /api
tags:
  - name: Categorias
  - name: Clientes
  - name: Compras
  - name: Países
  - name: Produtos
paths:
  /categories:
    $ref: './components/paths/category/Collection.yaml'
  /categories/{id}:
    $ref: './components/paths/category/Item.yaml'
  /countries:
    $ref: './components/paths/country/Collection.yaml'

components:
  schemas:
    Category:
      $ref: './components/schemas/category.yaml'
    Country:
      $ref: './components/schemas/country.yaml'
