type: object
properties:
  id:
    type: string
    format: uuid
    description: "Identificador do Produto"
    example: "123e4567-e89b-12d3-a456-426614174000"
  name:
    type: string
    maxLength: 100
    description: "Nome do Produto"
    example: "Vinho São Braz"
  category:
    $ref: './category.yaml'
  additional_info:
    type: string
    maxLength: 255
    description: "Descrição do Produto"